server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
      - id: productservice
        uri: lb://productservice
        predicates:
        - Path=/products,/products/{id}
      - id: reviewservice
        uri: lb://reviewservice
        predicates:
        - Path=/products/{productId}/reviews,/products/{productId}/reviews/{id},/reviews/all
        
management:
  endpoints:
    web:
      exposure:
        include: gateway
